---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fraud-detection-service
  title: Fraud Detection Service
  description: Detect Fraudulent invoices via Data Science Machine Learning Models
  annotations:
    github.com/project-slug: practicalli/fraud-detection
    github.com/team-slug: practicalli/Fraud-Detection
    backstage.io/techdocs-ref: dir:.
  tags:
    - clojure
  links:
    - url: https://github.com/practicalli
      title: Fraud Engineering Team
      icon: docs
    - url: https://github.com/practicalli/fraud-detection
      title: Fraud Detection Service Repository
      icon: github
spec:
  type: service
  lifecycle: development
  owner: practicalli
  system: risk-system
  providesApis:
    - fraud-detection-api
  consumesApis:
    - risk-api
    - fraud-model-api
