---
# --- Validate Backstage.io configuration files ---#
# https://github.com/marketplace/actions/backstage-entity-validator

# trigger workflow if yaml files `.backstage/` directory updated
name: Backstage Validator
on:
  pull_request:
    paths:
      - ".backstage/"

jobs:
  # Validate backstage configuration
  backstage-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RoadieHQ/backstage-entity-validator@v0.3.11
        with:
          path: ".backstage/*.yaml"
